Traceback (most recent call last):
  File "/home/trade/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/trade/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/trade/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/trade/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/trade/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/trade/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/home/trade/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/trade/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df1 = pd.DataFrame({
    '고객번호': [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    '이름': ['둘리', '도우너', '또치', '길동', '희동', '마이콜', '영희']
}, columns=['고객번호', '이름'])
df1
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-6d34454fb7b7>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m df1 = pd.DataFrame({
[0m[1;32m      2[0m     [0;34m'고객번호'[0m[0;34m:[0m [0;34m[[0m[0;36m1001[0m[0;34m,[0m [0;36m1002[0m[0;34m,[0m [0;36m1003[0m[0;34m,[0m [0;36m1004[0m[0;34m,[0m [0;36m1005[0m[0;34m,[0m [0;36m1006[0m[0;34m,[0m [0;36m1007[0m[0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0;34m'이름'[0m[0;34m:[0m [0;34m[[0m[0;34m'둘리'[0m[0;34m,[0m [0;34m'도우너'[0m[0;34m,[0m [0;34m'또치'[0m[0;34m,[0m [0;34m'길동'[0m[0;34m,[0m [0;34m'희동'[0m[0;34m,[0m [0;34m'마이콜'[0m[0;34m,[0m [0;34m'영희'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m }, columns=['고객번호', '이름'])
[1;32m      5[0m [0mdf1[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'pd' is not defined
NameError: name 'pd' is not defined

