Traceback (most recent call last):
  File "/home/trade/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/trade/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/trade/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/trade/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/trade/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/trade/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/home/trade/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/trade/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df = dd.read_csv("crime.csv", dtype=str, error_bad_lines=False, warn_bad_lines=False)
df
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-14-b6e396a7bd21>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mdf[0m [0;34m=[0m [0mdd[0m[0;34m.[0m[0mread_csv[0m[0;34m([0m[0;34m"crime.csv"[0m[0;34m,[0m [0mdtype[0m[0;34m=[0m[0mstr[0m[0;34m,[0m [0merror_bad_lines[0m[0;34m=[0m[0;32mFalse[0m[0;34m,[0m [0mwarn_bad_lines[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mdf[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/dask/dataframe/io/csv.py[0m in [0;36mread[0;34m(urlpath, blocksize, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)[0m
[1;32m    636[0m         [0;34m**[0m[0mkwargs[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    637[0m     ):
[0;32m--> 638[0;31m         return read_pandas(
[0m[1;32m    639[0m             [0mreader[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    640[0m             [0murlpath[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/dask/dataframe/io/csv.py[0m in [0;36mread_pandas[0;34m(reader, urlpath, blocksize, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)[0m
[1;32m    470[0m         [0msample[0m [0;34m=[0m [0mblocksize[0m[0;34m[0m[0;34m[0m[0m
[1;32m    471[0m     [0mb_lineterminator[0m [0;34m=[0m [0mlineterminator[0m[0;34m.[0m[0mencode[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 472[0;31m     b_out = read_bytes(
[0m[1;32m    473[0m         [0murlpath[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    474[0m         [0mdelimiter[0m[0;34m=[0m[0mb_lineterminator[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/dask/bytes/core.py[0m in [0;36mread_bytes[0;34m(urlpath, delimiter, not_zero, blocksize, sample, compression, include_path, **kwargs)[0m
[1;32m    123[0m                     [0;34m"To read, set blocksize=None"[0m[0;34m[0m[0;34m[0m[0m
[1;32m    124[0m                 )
[0;32m--> 125[0;31m             [0msize[0m [0;34m=[0m [0mfs[0m[0;34m.[0m[0minfo[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m[[0m[0;34m"size"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    126[0m             [0;32mif[0m [0msize[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    127[0m                 raise ValueError(

[0;32m~/anaconda3/lib/python3.8/site-packages/fsspec/implementations/local.py[0m in [0;36minfo[0;34m(self, path, **kwargs)[0m
[1;32m     56[0m     [0;32mdef[0m [0minfo[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mpath[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     57[0m         [0mpath[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_strip_protocol[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 58[0;31m         [0mout[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mstat[0m[0;34m([0m[0mpath[0m[0;34m,[0m [0mfollow_symlinks[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     59[0m         [0mdest[0m [0;34m=[0m [0;32mFalse[0m[0;34m[0m[0;34m[0m[0m
[1;32m     60[0m         [0;32mif[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mislink[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/home/trade/book/ds/01 python/crime.csv'
FileNotFoundError: [Errno 2] No such file or directory: '/home/trade/book/ds/01 python/crime.csv'

